version: "3.2"
services:

 nginx:
    image: christianheimke/demo-backend-proxy
    ports:
    - "8080:80"
 frontend:
    image: marcustechstarter/frontend-contmw:003

    depends_on:
      - nginx
    volumes:
      - ./data.csv:/etc/prometheus/prometheus.yml
      
 backend:
    image: marcustechstarter/demo_backendnodejsmw:001

    depends_on:
     - nginx
  