version: "3.2"
services:
  frontend:
    image: marcustechstarter/frontend-contmw:latest

    ports:
      - "5000:80"
    
  backend:
    image: marcustechstarter/demo_backendnodejsmw:latest

  
    ports:
     - "5001:5001"
  